AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

# Enable blue/green deployments using this Globals section. For instructions, see the AWS CodeStar User Guide:
# https://docs.aws.amazon.com/codestar/latest/userguide/how-to-modify-serverless-project.html?icmpid=docs_acs_rm_tr
#
# Globals:
#   Function:
#     AutoPublishAlias: live
#     DeploymentPreference:
#       Enabled: true
#       Type: Canary10Percent5Minutes

Resources:
  GetHorseName:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gethorsename/
      Handler: main
      Runtime: go1.x
      FunctionName: get-horse-name
      Role: !GetAtt BackingLambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /horsename
            Method: post
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMO_REGION: ap-northeast-1
  GetRaceName:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getracename/
      Handler: main
      Runtime: go1.x
      FunctionName: get-race-name
      Role: !GetAtt BackingLambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /racename
            Method: post
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMO_REGION: ap-northeast-1
  GetHorseId:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gethorseid/
      Handler: main
      Runtime: go1.x
      FunctionName: get-horse-id
      Role: !GetAtt BackingLambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /horseid
            Method: post
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMO_REGION: ap-northeast-1
  LineBotTest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: line_bot_test/
      Handler: main
      Runtime: go1.x
      Timeout: 10
      FunctionName: line-bot-test
      Role: !GetAtt BackingLambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /line_bot_test
            Method: post
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMO_REGION: ap-northeast-1
          CHANNEL_SECRET: AQICAHgV7FuJVSxQhBf3BpUF8BUNTLPIWQqw06CH4QqRXhlTJQG7qDG3mMYa2uxiFN8heL8WAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQdoPQOkLd23gef6mAgEQgDuqwQ28BIwd/o8+3idnZeL0rosyMu6JQh6vgf9yonFHAm2UB/2/ZPbMZB9WDmrGQg4oJ1eL2eTA7zbWdA==
          CHANNEL_TOKEN: AQICAHgV7FuJVSxQhBf3BpUF8BUNTLPIWQqw06CH4QqRXhlTJQEcT/QBCUKax+YqCSeUynU7AAABEDCCAQwGCSqGSIb3DQEHBqCB/jCB+wIBADCB9QYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxGkWNbtjNPodk/KJ0CARCAgcc8x6Pz1n098aHu5yTYa8UxDIdYzbt74mdL7U/4Tuv0gsmjzMpn5AzBufAxYDzhhmujJI6s7VY1p75QtcL+xltzqGdy+0eBCGuq+CP7u5BGxyiFYka1HmB0W8NdgmghBAKgxDkmxIPAr+vn7ClXfhav7oNkP8mu6bKH3hJzJtVZD+KDkT/FZheED1My4YllWrC33bGdAji6W6KxokD5DwhEe7eNV9KilvfnCR4mIvzdEBad3jvFogRctiJyBC1JHZ+PiQ0lcCQI
  GetCourseResult:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getcourseresult/
      Handler: main
      Runtime: go1.x
      FunctionName: get-course-result
      Role: !GetAtt BackingLambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /courseresult
            Method: post
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMO_REGION: ap-northeast-1
  GetRaceIndex:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getraceindex/
      Handler: main
      Runtime: go1.x
      FunctionName: get-race-index
      Role: !GetAtt BackingLambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /raceindex
            Method: post
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMO_REGION: ap-northeast-1
  BackingLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSConfigRulesExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      RoleName: CodestarExecLamdaRoleConnectDynamo
